# site title
title: JayMeng's Blog

# user name or organization name
user: JayMeng

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: f3c75c17e0637c40dc676022fceed8e8e73454c5 

# posts per page
perpage: 5


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
